services:
  tracefinity:
    image: ghcr.io/tracefinity/tracefinity
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/storage
    # environment:
      # GOOGLE_API_KEY: your-key
    restart: unless-stopped